
export const COMMON = {
  SERVER_REQUEST: 'SERVER_REQUEST',
  SERVER_SUCCESS: 'SERVER_SUCCESS',
  REMOVE_ERRORS: 'REMOVE_ERRORS',
  SET_ERRORS: 'SET_ERRORS'
}

export const USER = {
  SIGNED_IN: 'SIGNED_IN',
  SIGNED_OUT: 'SIGNED_OUT'
}